# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: SendEmail@2
  inputs:
    To: 'brijpatidar2003@gmail.com'
    From: '21ituos128@ddu.ac.in'
    Subject: 'Demo Mail'
    Body: 'This mail is sent you by azure devops. it means that github FSD/hostel-management is changed or commited.'
    BodyAsHtml: false
    AddAttachment: false
